# Generated by Django 3.2.16 on 2022-12-27 10:25

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('block', models.CharField(blank=True, max_length=200, null=True, verbose_name='Blok')),
                ('apartment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Daire')),
                ('period', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dönem')),
                ('period_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dönem Kodu')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad Soyad')),
                ('phone_one', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Lütfen doğru formatta giriniz: '+901234567890' ", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon 1')),
                ('phone_two', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Lütfen doğru formatta giriniz: '+901234567890' ", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon 2')),
                ('phone_three', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Lütfen doğru formatta giriniz: '+901234567890' ", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon 3')),
                ('tc', models.CharField(blank=True, max_length=200, null=True, verbose_name='TC')),
                ('circuit_start', models.CharField(blank=True, max_length=200, null=True, verbose_name='Devre Başlangıç')),
                ('circuit_finish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Devre Bitiş')),
            ],
            options={
                'verbose_name': 'Topluluk',
                'verbose_name_plural': 'Topluluk',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InterviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
            ],
            options={
                'verbose_name': 'Görüşme Durumu',
                'verbose_name_plural': 'Görüşme Durumu',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Başlık')),
                ('price_sales', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum 0.01', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Satış Fiyatı')),
                ('price_rent', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum 0.01', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kira Ücreti')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_community', to='training.community', verbose_name='Topluluk')),
                ('interview_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_interview_status', to='training.interviewstatus', verbose_name='Durum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_user', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Görüşme',
                'verbose_name_plural': 'Görüşme',
                'permissions': (('liste', 'Listeleme Yetkisi'), ('sil', 'Silme Yetkisi'), ('ekle', 'Ekleme Yetkisi'), ('guncelle', 'Güncelleme Yetkisi')),
                'default_permissions': (),
            },
        ),
    ]
