# Generated by Django 3.2.16 on 2022-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20221230_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='entrance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Giriş'),
        ),
    ]
