# Generated by Django 3.2.16 on 2022-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_community_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='note',
        ),
        migrations.AddField(
            model_name='interview',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='community',
            name='m2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='m2'),
        ),
        migrations.AlterField(
            model_name='community',
            name='period_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dönem Kodu'),
        ),
    ]
