# Generated by Django 3.2.16 on 2022-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20221230_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='text',
        ),
    ]
