# Generated by Django 3.2.16 on 2023-01-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_community_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='m2',
            field=models.IntegerField(blank=True, null=True, verbose_name='m2'),
        ),
    ]
