# Generated by Django 3.2.16 on 2023-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_community_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Not'),
        ),
    ]
