# Generated by Django 3.2.16 on 2023-01-01 12:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_community_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='price_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum 0.00', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kira Ücreti'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='price_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum 0.00', max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Satış Fiyatı'),
        ),
    ]
