# Generated by Django 3.2.16 on 2023-01-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20230101_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_interview_status', to='training.interviewstatus', verbose_name='Durum'),
        ),
    ]
