# Generated by Django 3.2.16 on 2023-01-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_interview_interview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='interview_status',
        ),
        migrations.RemoveField(
            model_name='community',
            name='note',
        ),
    ]
