# Generated by Django 3.2.16 on 2023-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_traininguser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininguser',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Durumu'),
        ),
    ]
