# Generated by Django 3.2.16 on 2022-12-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneAuthorizations',
        ),
    ]
