# Generated by Django 3.2.16 on 2022-12-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='groupList',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grup'),
        ),
    ]
