# Generated by Django 3.2.16 on 2022-12-31 16:21

import apps.common.fileUpload.userPath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_menu_grouplist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='cookie_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_profile_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='map',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_author',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='devremulk_kod',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Devremülk Kodları'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
