# Generated by Django 3.2.16 on 2023-01-03 16:32

import apps.common.fileUpload.userPath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_auto_20221231_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='devremulk_kod_d',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Devremülk Kodları Dikey'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='devremulk_kod',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Devremülk Kodları Yatay'),
        ),
    ]
